document:

  title: Azure-Sdk

  original:
    url: https://github.com/Azure/azure-sdk.git
    branch: main
    directory1: docs/dotnet/implementation.md
    directory2: docs/general/azurecore.md
    directory3: docs/ios/design.md
