name: push_from_weblate
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  build:
    name: push_from_weblate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: devrel-kr/I18N-For-Beginners
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'mdpo/settings_modified.json'
          prefix: settings
          masked: false
          
      - name: install python module
        run:
          pip install requests

      - name: Run python script
        env :
          BEARER_TOKEN : ${{ secrets.BEARER_TOKEN }}
        run : |
          for i in ${{ env.settings_path_sum_mdpo }}; do v=`echo $i | sed 's/.md//g' | sed 's/\///g'`; echo `python mdpo/push_from_weblate.py azure-sdk ${v,,}` >> result.txt ko; done
          cat result.txt
