name: push_from_weblate
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  job_1:
    name: push_from_weblate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: devrel-kr/I18N-For-Beginners
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'mdpo/settings_modified.json'
          prefix: settings
          masked: false
          
      - name: install python module
        run:
          pip install requests

      - name: Run python script
        env :
          BEARER_TOKEN : ${{ secrets.BEARER_TOKEN }}
        run : |
          commit=0
          for i in ${{ env.settings_path_sum_mdpo }}; do v=`echo $i | sed 's/.md//g' | sed 's/\///g'`;
          v1=`python mdpo/push_from_weblate.py azure-sdk ${v,,} ko`; if [[ ${v1} -eq 1 ]]; then commit=1; fi; done
          if [[ ${commit} -eq 1 ]]; then 
          content1=`echo $(git pull) | sed 's/^.*Fast-forward//'`
          sed -i '6i\'"  " mdpo/mdpo.md
          sed -i "6i\\$content1" mdpo/mdpo.md
          sed -i '6i\'"----------" mdpo/mdpo.md
          sed -i '6i\'"$(date +%Y)-$(date +%m)-$(date +%d) $(date +%H):$(date +%M):$(date +%S) (UTC)" mdpo/mdpo.md
          sed -i '6i\'"  " mdpo/mdpo.md
          git add .
          git config --global user.name ${{ secrets.USER_NAME_1 }}
          git config --global user.email ${{ secrets.USER_EMAIL_1 }}
          git commit -am "commit log."
          git push; fi;
  job_2:
    name: commit to gh-pages
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'main'
          TARGET_BRANCH: 'gh-pages'
        run: |
          git pull
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- mdpo/mdpo.md # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "commit to gh-pages"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch

