name: remote pull request
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - mdpo/ko/**
      
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'mdpo/settings_modified.json'
          prefix: settings
          masked: false
      
      - name: move files
        run : |
          mkdir -p docs/po
          for i in ${{ env.settings_path_mkdir }}; do mkdir -p docs/po/"$i"; done
          for i in ${{ env.settings_path_sum_mdpo }}; do v=`echo $i | sed 's/.md//g'` ; mv mdpo/ko/${v}.po docs/po/${v}.po ; done
          
      - name: Pull Request another repository
        uses: car-on-sale/action-pull-request-another-repo@v1.3.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAS_TOKEN }}
        with:
          source_folder: './docs/po'
          destination_repo: 'YYun-D/blog'
          destination_head_branch: 'test'
          user_email: ${{ secrets.USER_EMAIL_1 }}
          user_name: ${{ secrets.USER_NAME_1 }}
          pr_title: 'Update PO files'

