name: remote pull request
on:
  schedule:
    - cron: "0 0 * * 0"
      
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'mdpo/settings_modified.json'
          prefix: settings
          masked: false
      
      - name: move files
        run : |
          mkdir po
          for i in ${{ env.settings_path_mkdir }}; do v=`echo $i | sed 's/docs\///g'` ; mkdir -p po/${v} ; done
          for i in ${{ env.settings_path_sum_mdpo }}; do v1=`echo $i | sed 's/.md//g'` ; 
          v2=`echo $i | sed 's/.md//g' | sed 's/docs\///g'` ; mv mdpo/ko/${v1}.po po/${v2}.po ; done
          
      - name: Pull Request another repository
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAS_TOKEN }}
        with:
          source_folder: 'po'
          destination_repo: 'devrel-kr/azure-sdk-korean'
          destination_head_branch: 'update-po-files'
          destination_folder: 'docs'
          user_email: ${{ secrets.USER_EMAIL_1 }}
          user_name: ${{ secrets.USER_NAME_1 }}
          
          
