name: sync file
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  job_1:
    name: sync file from orgin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAS_TOKEN}}
          fetch-depth: 3
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'mdpo/settings_modified.json'
          prefix: settings
          masked: false
          
      - name: Sync files with dst-repsotiory
        uses: waroad/sync-files@main
        with:
          git-author-email: ${{ secrets.USER_EMAIL_1 }}
          git-author-name: ${{ secrets.USER_NAME_1 }}
          sync-repository: Azure/azure-sdk
          allow-files-pattern: ${{ env.settings_path_sum_sync }}
          sync-branch-name: ${{ env.settings_branch }}
          result-branch-name: main
  
  job_2:
    name: update log file.
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAS_TOKEN}}
          fetch-depth: 3
      - name: diff
        run: |
         date >> mdpo/mdpo.md
         echo "----------" >> mdpo/mdpo.md
         git diff --name-only HEAD~0 HEAD~1 >> mdpo/mdpo.md
         echo "modified." >> mdpo/mdpo.md
         echo "" >> mdpo/mdpo.md
         git add .
         git config --global user.name ${{ secrets.USER_NAME }}
         git config --global user.email ${{ secrets.USER_EMAIL }}
         git commit -am "commit log."
         git push
  
  
  job_3:
    name: commit to gh-pages
    runs-on: ubuntu-latest
    needs: job_2
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'main'
          TARGET_BRANCH: 'gh-pages'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- mdpo/mdpo.md # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "commit to gh-pages"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
