name: sync file
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  job_1:
    name: sync file from orgin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAS_TOKEN}}
          fetch-depth: 3
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'mdpo/settings_modified.json'
          prefix: settings
          masked: false
          
      - name: Sync files with dst-repsotiory
        uses: waroad/sync-files@main
        with:
          git-author-email: ${{ secrets.USER_EMAIL_1 }}
          git-author-name: ${{ secrets.USER_NAME_1 }}
          sync-repository: Azure/azure-sdk
          allow-files-pattern: ${{ env.settings_path_sum_sync }}
          sync-branch-name: ${{ env.settings_branch }}
          result-branch-name: main
  
  job_2:
    name: update log file.
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          token: ${{secrets.PAS_TOKEN}}
      - name: diff
        run: | 
         git pull
         echo "newest"
         echo $(git diff --stat HEAD~0 HEAD~1)
         echo "old"
         echo $(git diff --stat HEAD~1 HEAD~2)
         echo $(git diff --stat HEAD~2 HEAD~3)
         
         echo $(git diff --stat HEAD~3 HEAD~4)
         content1=`echo $(git diff --stat HEAD~1 HEAD~2 docs/)`
         sed -i '6i\'"  " mdpo/mdpo.md
         sed -i "6i\\$content1" mdpo/mdpo.md
         sed -i '6i\'"----------" mdpo/mdpo.md
         sed -i '6i\'"$(date +%Y)-$(date +%m)-$(date +%d) $(date +%H):$(date +%M):$(date +%S) (UTC)" mdpo/mdpo.md
         sed -i '6i\'"  " mdpo/mdpo.md
         git add .
         git config --global user.name ${{ secrets.USER_NAME_1 }}
         git config --global user.email ${{ secrets.USER_EMAIL_1 }}
         git commit -am "commit log."
         git push
